# https://help.github.com/en/actions

# https://github.com/actions
# https://github.com/actions/checkout
# https://github.com/actions/setup-node

name: CI on Push

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'website/**'
      - 'LICENSE'
      - '**.md'
      - '.gitignore'
      - '.npmignore'
      - '.prettier*'
      - '.vscode/**'
      - '.github/FUNDING.yml'
      - 'CHANGELOG.md'
      - '.github/workflows/publish-github-pages.yml'  


jobs:
  npm-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20, 22, 24]
        # node-version: [22]
        # https://github.com/actions/runner-images
        # os: [ 'ubuntu-24.04', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-15', 'windows-2025' ]
        os: [ 'ubuntu-24.04', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-15' ]
        # os: [ 'ubuntu-24.04' ]

    steps:
    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v6.0.1
      with:
        fetch-depth: 1

    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v6.1.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Show environment
      run: env

    - name: Install dependencies
      run: npm ci

    - name: Show tap configuration
      run: npm run test-tap-config-list

    - name: Run test
      run: npm run test-ci
      env:
        CI: true
